use crate::core::production_map::*;

pub(super) fn sample_map() -> ProductionMapDefinition {
    ProductionMapDefinition {
        id: "hotlunch-test".to_string(),
        product_code: "HOTLUNCH".to_string(),
        title: "Hotlunch test".to_string(),
        code: String::new(),
        order_number: String::new(),
        roll_count: None,
        width_mm: None,
        order_kg: None,
        base_length: None,
        nodes: vec![
            ProductionMapNode {
                id: "start".to_string(),
                kind: ProductionMapNodeKind::Start,
                title: "Start".to_string(),
                formula: None,
                role_code: String::new(),
                item_code: String::new(),
                qty_formula: String::new(),
                from_location: String::new(),
                to_location: String::new(),
                alternative_group_id: String::new(),
                alternative_group_label: String::new(),
                alternative_assigned_title: String::new(),
                rezka_kadr_count: None,
                rezka_label_length: None,
                x: 0.0,
                y: 0.0,
            },
            ProductionMapNode {
                id: "formula".to_string(),
                kind: ProductionMapNodeKind::Formula,
                title: "CPP hisob".to_string(),
                formula: Some(ProductionFormula {
                    target: "cpp_kg".to_string(),
                    expression: "order_qty * 1.08".to_string(),
                }),
                role_code: String::new(),
                item_code: "CPP".to_string(),
                qty_formula: String::new(),
                from_location: String::new(),
                to_location: String::new(),
                alternative_group_id: String::new(),
                alternative_group_label: String::new(),
                alternative_assigned_title: String::new(),
                rezka_kadr_count: None,
                rezka_label_length: None,
                x: 0.0,
                y: 0.0,
            },
            ProductionMapNode {
                id: "task".to_string(),
                kind: ProductionMapNodeKind::Task,
                title: "Rezkaga yuborish".to_string(),
                formula: None,
                role_code: "rezkachi".to_string(),
                item_code: String::new(),
                qty_formula: "cpp_kg".to_string(),
                from_location: "CPP ombor".to_string(),
                to_location: "Rezka apparat".to_string(),
                alternative_group_id: String::new(),
                alternative_group_label: String::new(),
                alternative_assigned_title: String::new(),
                rezka_kadr_count: None,
                rezka_label_length: None,
                x: 0.0,
                y: 0.0,
            },
            ProductionMapNode {
                id: "end".to_string(),
                kind: ProductionMapNodeKind::End,
                title: "End".to_string(),
                formula: None,
                role_code: String::new(),
                item_code: String::new(),
                qty_formula: String::new(),
                from_location: String::new(),
                to_location: String::new(),
                alternative_group_id: String::new(),
                alternative_group_label: String::new(),
                alternative_assigned_title: String::new(),
                rezka_kadr_count: None,
                rezka_label_length: None,
                x: 0.0,
                y: 0.0,
            },
        ],
        edges: vec![
            ProductionMapEdge {
                from: "start".to_string(),
                to: "formula".to_string(),
                branch: String::new(),
            },
            ProductionMapEdge {
                from: "formula".to_string(),
                to: "task".to_string(),
                branch: String::new(),
            },
            ProductionMapEdge {
                from: "task".to_string(),
                to: "end".to_string(),
                branch: String::new(),
            },
        ],
    }
}

pub(super) fn apparatus_stage_map(id: &str, apparatus: &str) -> ProductionMapDefinition {
    ProductionMapDefinition {
        id: id.to_string(),
        product_code: format!("{id}-product"),
        title: id.to_string(),
        code: String::new(),
        order_number: String::new(),
        roll_count: None,
        width_mm: None,
        order_kg: None,
        base_length: None,
        nodes: vec![
            ProductionMapNode {
                id: "start".to_string(),
                kind: ProductionMapNodeKind::Start,
                title: "Start".to_string(),
                formula: None,
                role_code: String::new(),
                item_code: String::new(),
                qty_formula: String::new(),
                from_location: String::new(),
                to_location: String::new(),
                alternative_group_id: String::new(),
                alternative_group_label: String::new(),
                alternative_assigned_title: String::new(),
                rezka_kadr_count: None,
                rezka_label_length: None,
                x: 0.0,
                y: 0.0,
            },
            ProductionMapNode {
                id: "apparatus".to_string(),
                kind: ProductionMapNodeKind::Apparatus,
                title: apparatus.to_string(),
                formula: None,
                role_code: String::new(),
                item_code: String::new(),
                qty_formula: String::new(),
                from_location: String::new(),
                to_location: String::new(),
                alternative_group_id: String::new(),
                alternative_group_label: String::new(),
                alternative_assigned_title: String::new(),
                rezka_kadr_count: None,
                rezka_label_length: None,
                x: 0.0,
                y: 132.0,
            },
            ProductionMapNode {
                id: "end".to_string(),
                kind: ProductionMapNodeKind::End,
                title: "End".to_string(),
                formula: None,
                role_code: String::new(),
                item_code: String::new(),
                qty_formula: String::new(),
                from_location: String::new(),
                to_location: String::new(),
                alternative_group_id: String::new(),
                alternative_group_label: String::new(),
                alternative_assigned_title: String::new(),
                rezka_kadr_count: None,
                rezka_label_length: None,
                x: 0.0,
                y: 264.0,
            },
        ],
        edges: vec![
            ProductionMapEdge {
                from: "start".to_string(),
                to: "apparatus".to_string(),
                branch: String::new(),
            },
            ProductionMapEdge {
                from: "apparatus".to_string(),
                to: "end".to_string(),
                branch: String::new(),
            },
        ],
    }
}

pub(super) fn condition_map() -> ProductionMapDefinition {
    ProductionMapDefinition {
        id: "branch-test".to_string(),
        product_code: "HOTLUNCH".to_string(),
        title: "Branch test".to_string(),
        code: String::new(),
        order_number: String::new(),
        roll_count: None,
        width_mm: None,
        order_kg: None,
        base_length: None,
        nodes: vec![
            ProductionMapNode {
                id: "start".to_string(),
                kind: ProductionMapNodeKind::Start,
                title: "Start".to_string(),
                formula: None,
                role_code: String::new(),
                item_code: String::new(),
                qty_formula: String::new(),
                from_location: String::new(),
                to_location: String::new(),
                alternative_group_id: String::new(),
                alternative_group_label: String::new(),
                alternative_assigned_title: String::new(),
                rezka_kadr_count: None,
                rezka_label_length: None,
                x: 0.0,
                y: 0.0,
            },
            ProductionMapNode {
                id: "large_order".to_string(),
                kind: ProductionMapNodeKind::Condition,
                title: "Katta partiyami".to_string(),
                formula: Some(ProductionFormula {
                    target: String::new(),
                    expression: "order_qty >= 100".to_string(),
                }),
                role_code: String::new(),
                item_code: String::new(),
                qty_formula: String::new(),
                from_location: String::new(),
                to_location: String::new(),
                alternative_group_id: String::new(),
                alternative_group_label: String::new(),
                alternative_assigned_title: String::new(),
                rezka_kadr_count: None,
                rezka_label_length: None,
                x: 0.0,
                y: 0.0,
            },
            ProductionMapNode {
                id: "large_task".to_string(),
                kind: ProductionMapNodeKind::Task,
                title: "Katta partiya".to_string(),
                formula: None,
                role_code: "rezkachi".to_string(),
                item_code: String::new(),
                qty_formula: "order_qty / 6".to_string(),
                from_location: "CPP ombor".to_string(),
                to_location: "Rezka apparat".to_string(),
                alternative_group_id: String::new(),
                alternative_group_label: String::new(),
                alternative_assigned_title: String::new(),
                rezka_kadr_count: None,
                rezka_label_length: None,
                x: 0.0,
                y: 0.0,
            },
            ProductionMapNode {
                id: "small_task".to_string(),
                kind: ProductionMapNodeKind::Task,
                title: "Oddiy partiya".to_string(),
                formula: None,
                role_code: "operator".to_string(),
                item_code: String::new(),
                qty_formula: String::new(),
                from_location: String::new(),
                to_location: String::new(),
                alternative_group_id: String::new(),
                alternative_group_label: String::new(),
                alternative_assigned_title: String::new(),
                rezka_kadr_count: None,
                rezka_label_length: None,
                x: 0.0,
                y: 0.0,
            },
            ProductionMapNode {
                id: "end".to_string(),
                kind: ProductionMapNodeKind::End,
                title: "End".to_string(),
                formula: None,
                role_code: String::new(),
                item_code: String::new(),
                qty_formula: String::new(),
                from_location: String::new(),
                to_location: String::new(),
                alternative_group_id: String::new(),
                alternative_group_label: String::new(),
                alternative_assigned_title: String::new(),
                rezka_kadr_count: None,
                rezka_label_length: None,
                x: 0.0,
                y: 0.0,
            },
        ],
        edges: vec![
            ProductionMapEdge {
                from: "start".to_string(),
                to: "large_order".to_string(),
                branch: String::new(),
            },
            ProductionMapEdge {
                from: "large_order".to_string(),
                to: "large_task".to_string(),
                branch: "true".to_string(),
            },
            ProductionMapEdge {
                from: "large_order".to_string(),
                to: "small_task".to_string(),
                branch: "false".to_string(),
            },
            ProductionMapEdge {
                from: "large_task".to_string(),
                to: "end".to_string(),
                branch: String::new(),
            },
            ProductionMapEdge {
                from: "small_task".to_string(),
                to: "end".to_string(),
                branch: String::new(),
            },
        ],
    }
}
