fn catalog_routes() -> Router<AppState> {
    Router::new()
        .route(
            "/v1/mobile/admin/role-assignments",
            any(admin::role_assignments),
        )
        .route("/v1/mobile/admin/suppliers", any(admin::suppliers))
        .route("/v1/mobile/admin/users/list", any(admin::user_list))
        .route(
            "/v1/mobile/admin/profile/avatar/view",
            get(admin::admin_profile_avatar_view),
        )
        .route("/v1/mobile/admin/suppliers/list", any(admin::supplier_list))
        .route(
            "/v1/mobile/admin/suppliers/summary",
            any(admin::supplier_summary),
        )
        .route(
            "/v1/mobile/admin/suppliers/detail",
            any(admin::supplier_detail),
        )
        .route(
            "/v1/mobile/admin/suppliers/inactive",
            any(admin::inactive_suppliers),
        )
        .route(
            "/v1/mobile/admin/suppliers/items/assigned",
            any(admin::assigned_supplier_items),
        )
        .route(
            "/v1/mobile/admin/suppliers/status",
            any(admin::supplier_status),
        )
        .route(
            "/v1/mobile/admin/suppliers/phone",
            any(admin::supplier_phone),
        )
        .route(
            "/v1/mobile/admin/suppliers/items",
            any(admin::supplier_items),
        )
        .route(
            "/v1/mobile/admin/suppliers/items/add",
            any(admin::supplier_item_add),
        )
        .route(
            "/v1/mobile/admin/suppliers/items/remove",
            any(admin::supplier_item_remove),
        )
        .route(
            "/v1/mobile/admin/suppliers/code/regenerate",
            any(admin::supplier_code_regenerate),
        )
        .route(
            "/v1/mobile/admin/suppliers/remove",
            any(admin::supplier_remove),
        )
        .route(
            "/v1/mobile/admin/suppliers/restore",
            any(admin::supplier_restore),
        )
        .route("/v1/mobile/admin/customers", any(admin::customers))
        .route(
            "/v1/mobile/admin/material-taminotchilar",
            any(admin::material_taminotchilar),
        )
        .route(
            "/v1/mobile/admin/material-taminotchilar/detail",
            any(admin::material_taminotchi_detail),
        )
        .route(
            "/v1/mobile/admin/material-taminotchilar/phone",
            any(admin::material_taminotchi_phone),
        )
        .route(
            "/v1/mobile/admin/material-taminotchilar/item-groups",
            any(admin::material_taminotchi_item_groups),
        )
        .route(
            "/v1/mobile/admin/material-taminotchilar/code/regenerate",
            any(admin::material_taminotchi_code_regenerate),
        )
        .route("/v1/mobile/admin/customers/list", any(admin::customer_list))
        .route(
            "/v1/mobile/admin/customers/detail",
            any(admin::customer_detail),
        )
        .route(
            "/v1/mobile/admin/customers/phone",
            any(admin::customer_phone),
        )
        .route(
            "/v1/mobile/admin/customers/code/regenerate",
            any(admin::customer_code_regenerate),
        )
        .route(
            "/v1/mobile/admin/customers/items/add",
            any(admin::customer_item_add),
        )
        .route(
            "/v1/mobile/admin/customers/items/remove",
            any(admin::customer_item_remove),
        )
        .route(
            "/v1/mobile/admin/customers/remove",
            any(admin::customer_remove),
        )
        .route("/v1/mobile/admin/items", any(admin::items))
        .route("/v1/mobile/admin/items/uoms", any(admin::item_uoms))
        .route("/v1/mobile/admin/items/detail", any(admin::item_detail))
        .route(
            "/v1/mobile/admin/apparatus/options",
            any(admin::apparatus_options),
        )
        .route("/v1/mobile/admin/apparatus", any(admin::apparatus))
        .route(
            "/v1/mobile/admin/apparatus-collections",
            any(admin::apparatus_collections),
        )
        .route(
            "/v1/mobile/admin/apparatus-collections/{id}",
            any(admin::apparatus_collection),
        )
        .route(
            "/v1/mobile/admin/apparatus/{id}",
            any(admin::apparatus_detail),
        )
        .route(
            "/v1/mobile/admin/apparatus/{id}/aasx",
            any(admin::apparatus_aasx).layer(DefaultBodyLimit::max(admin::MAX_AASX_UPLOAD_BYTES)),
        )
        .route(
            "/v1/mobile/admin/factory-locations",
            any(admin::factory_locations),
        )
        .route(
            "/v1/mobile/admin/factory-locations/{id}",
            any(admin::factory_location),
        )
        .route(
            "/v1/mobile/admin/factory-locations/{id}/apparatus",
            any(admin::factory_location_apparatus),
        )
}
