fn inventory_and_system_routes() -> Router<AppState> {
    Router::new()
        .route(
            "/v1/mobile/admin/inventory/locations",
            any(admin::inventory_locations),
        )
        .route(
            "/v1/mobile/admin/inventory/assets",
            any(admin::inventory_assets),
        )
        .route(
            "/v1/mobile/admin/inventory/relocations",
            any(admin::inventory_relocations),
        )
        .route(
            "/v1/mobile/admin/inventory/relocations/batch",
            any(admin::inventory_relocations_batch),
        )
        .route(
            "/v1/mobile/admin/inventory/returns/batch",
            any(admin::inventory_returns_batch),
        )
        .route(
            "/v1/mobile/admin/inventory/transfers",
            any(admin::inventory_transfers),
        )
        .route(
            "/v1/mobile/admin/inventory/transfers/{id}/{action}",
            any(admin::inventory_transfer_action),
        )
        .route("/v1/mobile/admin/warehouses", any(admin::warehouses))
        .route(
            "/v1/mobile/admin/warehouses/live",
            get(admin::warehouse_live),
        )
        .route(
            "/v1/mobile/admin/warehouses/summary",
            any(admin::warehouse_summaries),
        )
        .route(
            "/v1/mobile/admin/warehouses/items",
            any(admin::warehouse_items),
        )
        .route(
            "/v1/mobile/admin/warehouses/assignments",
            any(admin::warehouse_assignments),
        )
        .route(
            "/v1/mobile/admin/items/bulk-move-group",
            any(admin::items_bulk_move_group),
        )
        .route(
            "/v1/mobile/admin/item-groups/tree",
            any(admin::item_group_tree),
        )
        .route("/v1/mobile/admin/item-groups", any(admin::item_groups))
        .route("/v1/mobile/admin/activity", any(admin::activity))
        .route(
            "/v1/mobile/admin/system/monitor",
            get(admin::system_monitor),
        )
        .route(
            "/v1/mobile/admin/system/monitor/live",
            get(admin::system_monitor_live),
        )
        .route(
            "/v1/mobile/admin/system/backups",
            post(admin::system_backup_create),
        )
        .route(
            "/v1/mobile/admin/system/backups/{id}/download",
            get(admin::system_backup_download),
        )
        .route(
            "/v1/mobile/admin/system/backups/import",
            post(admin::system_backup_import),
        )
        .route(
            "/v1/mobile/admin/emergency-reset/orders",
            post(admin::reset_orders),
        )
        .route(
            "/v1/mobile/admin/werka/code/regenerate",
            any(admin::werka_code_regenerate),
        )
}
