fn material_routes() -> Router<AppState> {
    Router::new()
        .route(
            "/v1/mobile/admin/raw-material-rules",
            any(admin::raw_material_rules),
        )
        .route(
            "/v1/mobile/admin/calculate-materials",
            any(admin::calculate_materials),
        )
        .route(
            "/v1/mobile/admin/raw-material-start-requirements",
            any(admin::raw_material_start_requirements),
        )
        .route(
            "/v1/mobile/admin/raw-material-assignments/lookup",
            any(admin::raw_material_assignment_lookup),
        )
        .route(
            "/v1/mobile/admin/raw-material-assignments/orders",
            any(admin::raw_material_assignment_orders),
        )
        .route(
            "/v1/mobile/admin/raw-material-assignments/candidates",
            any(admin::raw_material_assignment_candidates),
        )
        .route(
            "/v1/mobile/admin/raw-material-assignments/candidate-orders",
            any(admin::raw_material_assignment_candidate_orders),
        )
        .route(
            "/v1/mobile/admin/raw-material-assignments/diagnostics",
            any(admin::raw_material_assignment_diagnostics),
        )
        .route(
            "/v1/mobile/admin/raw-material-assignments",
            any(admin::raw_material_assignments),
        )
        .route(
            "/v1/mobile/admin/raw-material-intake",
            any(admin::raw_material_intake),
        )
        .route(
            "/v1/mobile/admin/raw-material-intake-candidates",
            any(admin::raw_material_intake_candidates),
        )
        .route(
            "/v1/mobile/admin/raw-material-stock",
            any(admin::raw_material_stock),
        )
        .route(
            "/v1/mobile/admin/raw-material-stock/reprint/prepare",
            any(admin::raw_material_stock_reprint_prepare),
        )
        .route(
            "/v1/mobile/admin/raw-material-stock/reprint/confirm",
            any(admin::raw_material_stock_reprint_confirm),
        )
        .route(
            "/v1/mobile/admin/raw-material-history",
            any(admin::raw_material_history),
        )
}
