fn production_routes() -> Router<AppState> {
    Router::new()
        .route(
            "/v1/mobile/admin/production-maps",
            any(admin::production_maps),
        )
        .route(
            "/v1/mobile/admin/production-maps/run",
            any(admin::production_map_run),
        )
        .route(
            "/v1/mobile/admin/production-maps/audit",
            get(admin::production_map_audit),
        )
        .route(
            "/v1/mobile/admin/production-maps/capacity",
            any(admin::production_map_capacity),
        )
        .route(
            "/v1/mobile/admin/production-maps/capacity/downtime",
            any(admin::production_map_capacity_downtime),
        )
        .route(
            "/v1/mobile/admin/production-maps/schedule",
            any(admin::production_map_schedule),
        )
        .route(
            "/v1/mobile/admin/production-maps/schedule/cancel",
            any(admin::production_map_schedule_cancel),
        )
        .route(
            "/v1/mobile/admin/production-maps/with-order",
            any(admin::production_map_save_with_order),
        )
        .route(
            "/v1/mobile/admin/production-maps/opening-wip",
            any(admin::production_map_opening_wip),
        )
        .route(
            "/v1/mobile/admin/production-maps/opening-wip/print",
            any(admin::production_map_opening_wip_print),
        )
        .route(
            "/v1/mobile/admin/production-maps/opening-wip/lookup",
            any(admin::production_map_opening_wip_lookup),
        )
        .route(
            "/v1/mobile/admin/production-maps/opening-wip/qr/report",
            any(admin::production_map_opening_wip_qr_report),
        )
        .route(
            "/v1/mobile/admin/training/apparatus",
            any(admin::training_apparatus_modes),
        )
        .route(
            "/v1/mobile/admin/training/restart",
            post(admin::training_restart),
        )
        .route(
            "/v1/mobile/admin/training/completed-orders",
            get(admin::training_completed_orders),
        )
        .route(
            "/v1/mobile/admin/training/statuses",
            get(admin::training_order_statuses),
        )
        .route(
            "/v1/mobile/admin/training/production-maps",
            any(admin::training_production_maps),
        )
        .route(
            "/v1/mobile/admin/training/production-maps/with-order",
            any(admin::training_production_map_save_with_order),
        )
        .route(
            "/v1/mobile/admin/training/input-batches",
            any(admin::training_input_batches),
        )
        .route(
            "/v1/mobile/admin/training/raw-material-assignments",
            any(admin::training_raw_material_assignments),
        )
        .route(
            "/v1/mobile/admin/training/images",
            any(admin::training_order_image_upload).layer(DefaultBodyLimit::max(6 * 1024 * 1024)),
        )
        .route(
            "/v1/mobile/admin/training/images/view",
            any(admin::training_order_image_view),
        )
        .route(
            "/v1/mobile/admin/production-maps/move",
            any(admin::production_map_move),
        )
        .route(
            "/v1/mobile/admin/production-maps/move-batch",
            any(admin::production_map_move_batch),
        )
        .route(
            "/v1/mobile/admin/production-maps/apparatus-transfer",
            any(admin::production_map_apparatus_transfer),
        )
        .route(
            "/v1/mobile/admin/production-maps/sequence",
            any(admin::production_map_sequence),
        )
        .route(
            "/v1/mobile/admin/production-maps/queue-policies",
            any(admin::production_map_queue_policies),
        )
        .route(
            "/v1/mobile/admin/production-maps/live",
            any(admin::production_map_live),
        )
        .route(
            "/v1/mobile/admin/production-maps/order-image/view",
            any(admin::production_map_order_image_view),
        )
        .route(
            "/v1/mobile/admin/production-maps/completed-orders",
            any(admin::production_map_completed_orders),
        )
        .route(
            "/v1/mobile/admin/production-maps/completion-requests",
            any(admin::production_map_completion_requests),
        )
        .route(
            "/v1/mobile/admin/production-maps/completion-requests/decision",
            any(admin::production_map_completion_request_decision),
        )
        .route(
            "/v1/mobile/admin/production-maps/completion-request-decisions",
            any(admin::production_map_completion_request_decisions),
        )
        .route(
            "/v1/mobile/admin/production-maps/closed-orders",
            any(admin::production_map_closed_orders),
        )
        .route(
            "/v1/mobile/admin/production-maps/queue-action",
            any(admin::production_map_queue_action),
        )
        .route(
            "/v1/mobile/admin/production-maps/laminatsiya-astatka",
            any(admin::production_map_laminatsiya_astatka),
        )
        .route(
            "/v1/mobile/admin/production-maps/rezka-astatka",
            any(admin::production_map_rezka_astatka),
        )
        .route(
            "/v1/mobile/admin/production-maps/order-control",
            post(admin::production_map_order_control),
        )
        .route(
            "/v1/mobile/admin/production-maps/qolip-validate",
            any(admin::production_map_qolip_validate),
        )
        .route(
            "/v1/mobile/admin/production-maps/progress-qr/lookup",
            any(admin::production_map_progress_qr_lookup),
        )
        .route(
            "/v1/mobile/admin/production-maps/progress-qr/history",
            any(admin::production_map_progress_qr_history),
        )
        .route(
            "/v1/mobile/admin/production-maps/progress-qr/correct",
            post(admin::production_map_progress_batch_correct),
        )
        .route(
            "/v1/mobile/admin/production-maps/progress-qr/report",
            any(admin::production_map_progress_qr_report),
        )
        .route(
            "/v1/mobile/admin/production-maps/progress-qr/reprint",
            any(admin::production_map_progress_qr_reprint),
        )
        .route(
            "/v1/mobile/admin/production-maps/paddons",
            any(admin::production_map_paddons),
        )
        .route(
            "/v1/mobile/admin/production-maps/paddons/detail",
            any(admin::production_map_paddon_detail),
        )
        .route(
            "/v1/mobile/admin/production-maps/paddons/qr/report",
            any(admin::production_map_paddon_qr_report),
        )
        .route(
            "/v1/mobile/admin/production-maps/paddons/qr/print",
            any(admin::production_map_paddon_qr_print),
        )
        .route(
            "/v1/mobile/admin/production-maps/paddons/create",
            any(admin::production_map_paddon_create),
        )
        .route(
            "/v1/mobile/admin/production-maps/paddons/items/add",
            any(admin::production_map_paddon_item_add),
        )
        .route(
            "/v1/mobile/admin/production-maps/paddons/items/add-batch",
            any(admin::production_map_paddon_items_add),
        )
        .route(
            "/v1/mobile/admin/production-maps/paddons/items/remove",
            any(admin::production_map_paddon_item_remove),
        )
        .route(
            "/v1/mobile/admin/production-maps/paddons/items/remove-batch",
            any(admin::production_map_paddon_items_remove),
        )
        .route(
            "/v1/mobile/admin/production-maps/wip-batches",
            any(admin::production_map_wip_batches),
        )
        .route(
            "/v1/mobile/admin/production-maps/finished-goods/receive",
            any(admin::production_map_finished_goods_receive),
        )
}
